User.create! :name => 'John 0', :email => 'john@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret'
User.create! :name => 'John 1', :email => 'john@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret'
User.create! :name => 'John A', :email => 'john@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret'
User.create! :name => 'John B', :email => 'john@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret'

User.create! :name => 'John C', :email => 'john@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret'
User.create! :name => 'John D', :email => 'john@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret'
User.create! :name => 'John F', :email => 'john@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret'
User.create! :name => 'John q', :email => 'john@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret'

User.create! :name => 'John w', :email => 'john@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret'
User.create! :name => 'John e', :email => 'john@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret'
User.create! :name => 'John r', :email => 'john@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret'
User.create! :name => 'John t', :email => 'john@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret'

User.create! :name => 'John r', :email => 'john@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret'
User.create! :name => 'John t', :email => 'john@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret'
User.create! :name => 'John y', :email => 'john@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret'
User.create! :name => 'John u', :email => 'john@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret'
User.create! :name => 'John i', :email => 'john@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret'
User.create! :name => 'John o', :email => 'john@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret'
User.create! :name => 'John p', :email => 'john@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret'
User.create! :name => 'John 9', :email => 'john@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret'
